spring:
  application:
    name: gallery

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gallery
    username: root
    password: ${DB_PWD}

  jpa:
    hibernate:
      ddl-auto: update
my_security:
  key: ${SECURITY_KEY}